Update validate_secrets_debug.yml

diff --git a/.github/workflows/validate_secrets_debug.yml b/.github/workflows/validate_secrets_debug.yml
--- a/.github/workflows/validate_secrets_debug.yml
+++ b/.github/workflows/validate_secrets_debug.yml
@@ -16,4 +16,50 @@ jobs:
         run: |
           echo "Length of GH_PAT: ${#GH_PAT}"
           echo "Start: ${GH_PAT:0:4}****"
-          echo "End:
+          echo "End: ****${GH_PAT: -4}"
+        shell: bash
+        env:
+          GH_PAT: ${{ secrets.GH_PAT }}
+
+      - name: Validate Access Token
+        id: access-token
+        run: |
+          set -o pipefail
+
+          GH_PAT_CLASSIC_PATTERN='^ghp_[a-zA-Z0-9]{36}$'
+          GH_PAT_FINE_GRAINED_PATTERN='^github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}$'
+
+          if [ -z "$GH_PAT" ]; then
+            failed=true
+            echo "::error::The GH_PAT secret is unset or empty. Set it and try again."
+          else
+            if [[ $GH_PAT =~ $GH_PAT_CLASSIC_PATTERN ]]; then
+              provides_scopes=true
+              echo "The GH_PAT secret is a structurally valid classic token."
+            elif [[ $GH_PAT =~ $GH_PAT_FINE_GRAINED_PATTERN ]]; then
+              echo "The GH_PAT secret is a structurally valid fine-grained token."
+            else
+              unknown_format=true
+              echo "The GH_PAT secret does not have a known token format."
+            fi
+
+            if ! scopes=$(curl -sS -f -I -H "Authorization: token $GH_PAT" https://api.github.com | { grep -i '^x-oauth-scopes:' || true; } | cut -d ' ' -f2- | tr -d '\r'); then
+              failed=true
+              echo "::error::Unable to connect to GitHub using the GH_PAT secret. Check the token validity or permissions."
+            elif [[ $scopes =~ workflow ]]; then
+              echo "The GH_PAT secret has repo and workflow permissions."
+              echo "has_workflow_permission=true" >> $GITHUB_OUTPUT
+            elif [[ $scopes =~ repo ]]; then
+              echo "The GH_PAT secret has repo (but not workflow) permissions."
+            elif [ $provides_scopes ]; then
+              failed=true
+              echo "::error::The GH_PAT secret is valid but missing necessary scopes: $scopes"
+            else
+              echo "Assuming default scopes are present."
+              echo "has_workflow_permission=true" >> $GITHUB_OUTPUT
+            fi
+          fi
+
+          if [ $failed ]; then
+            exit 2
+          fi
